---
# tasks file for update_servers

- name: Install system updates for debian systems
  apt:
    name: '*'
    state: latest
    update_cache: yes
    #cache_valid_time: 3600
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution == "CentOS"